"use client"
import Link from "next/link";
import { usePathname } from "next/navigation";
import {useState} from 'react';


// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js'
// }

const navlinks = [
    {name: "Register", href: "/register"},
    {name: "Login", href: "/login"},
    {name: "Forgotpassword", href: "/forgotpassword"}
]

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    const pathname = usePathname();
    const [input, setInput] = useState("");

    return (
        <> 
            <div className="p-4">
                <input 
                value={input} 
                onChange={(e) => setInput(e.target.value)} 
                className="outline rounded-sm"/>
            </div>
            {children} 
            {
                navlinks.map((link) => {
                    const isActive = pathname.startsWith(link.href)
                    return (
                        <Link 
                            href={link.href} 
                            key={link.name}
                            className={ isActive ? "text-yellow-400 font-serif font-bold" : "text-blue-400 font-serif font-bold"} 
                        >
                        {link.name}
                        </Link>
                    )
                })
            }
        </>
    );
}