import React from 'react'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Rusty Chase",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>Profile page</div>
  )
}

export default page